[package]
name = "WebClient"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "0.3"
url = "2.2"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"